---
- name: Ensure dependencies are installed.
  apt: pkg={{ item }} state=installed
  with_items:
    - curl
    - git

- name: Add Jenkins apt repository key.
  apt_key:
    data: "{{ lookup('file', 'jenkins-ci.org.key') }}"
    state: present
    validate_certs: no

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes

- name: Ensure Jenkins is installed.
  apt: pkg=jenkins state=installed

- name: Tweak the configuration
  lineinfile: dest=/etc/default/jenkins backup=yes regexp="^JAVA_ARGS=" line='JAVA_ARGS="-Djava.awt.headless=true {{ java_proxy_opts }}"'
