---
- name: Ensure dependencies are installed.
  apt: pkg={{ item }} state=installed
  with_items:
    - curl
    - git
    - python-virtualenv
    - python-dev

- name: Add Jenkins apt repository key.
  apt_key:
    data: "{{ lookup('file', 'jenkins-ci.org.key') }}"
    state: present
    validate_certs: no

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes

- name: Ensure Jenkins is installed.
  apt: pkg=jenkins state=installed

- name: Update /etc/default/jenkins
  template: src=etc/default/jenkins.j2 dest=/etc/default/jenkins
  register: etc_default_jenkins

- name: Results from /etc/default/jenkins template
  debug: var=etc_default_jenkins

# this has to be executed inside this task so that the rest of the
# dynamic config can take place - this is why we don't use a handler
- name: restart jenkins
  service: name=jenkins state=restarted
  when: etc_default_jenkins.changed
